# Target to compile the C++ program
FizzBuzz: FizzBuzz.o
    g++ FizzBuzz.o -o FizzBuzz

# Target to compile the object file
FizzBUzz.o: FizzBuzz.cpp
    g++ -c FizzBuzz.cpp -o FizzBuzz.o

# Target to run the program
run: FizzBuzz
    ./FizzBuzz

# Target to clean up compiled files
clean :
    rm -f FizzBuzz.o FizzBuzz
